name: 最新版

on: [push]

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64]
      fail-fast: true
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: "1.20"
      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build binary file
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd hack
          bash releaser.sh
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: mastergo-font-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          path: output/mastergo-font-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
