name: 发行版

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build And Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: "1.20"
      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build binary file
        run: |
          cd hack
          bash release.sh

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: output/*
          draft: true
